production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %> 
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

development:
  adapter: sqlite3
  database: db/babies-development.sqlite3

test:
  adapter: sqlite3
  database: db/babies-test.sqlite3
