production:
  adapter: postgresql
  encoding: unicode
  database: ebdb
  username: gregory4209
  password: password
  host: aag1fjlxgxz3gt.chexux3wan9g.us-west-2.rds.amazonaws.com:5432
  port: 5432

development:
  adapter: sqlite3
  database: db/babies-development.sqlite3

test:
  adapter: sqlite3
  database: db/babies-test.sqlite3
