production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ebdb
  username: gregory4209
  password: password
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: 5432

development:
  adapter: sqlite3
  database: db/babies-development.sqlite3

test:
  adapter: sqlite3
  database: db/babies-test.sqlite3
